// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Columbo.Minesweeper.Specs.Uat.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Revealing Tiles")]
    public partial class RevealingTilesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RevealingTiles.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Revealing Tiles", "In order to identify mines\r\nAs a player \r\nI want to be able to click on a tile\r\na" +
                    "nd see how many mines surround that tile", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Click a tile that is next to a mine on a minefield that contains one mine")]
        public virtual void ClickATileThatIsNextToAMineOnAMinefieldThatContainsOneMine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Click a tile that is next to a mine on a minefield that contains one mine", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have started a new game \"minefield size of 9 x 9 (10 mines)\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column"});
            table1.AddRow(new string[] {
                        "1",
                        "1"});
#line 9
 testRunner.And("the minefield contains the following mines:", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column",
                        "NumberOfMinesSurroundedBy"});
            table2.AddRow(new string[] {
                        "0",
                        "0",
                        "1"});
#line 12
 testRunner.And("the following tiles are surrounded by mines:", ((string)(null)), table2);
#line 15
 testRunner.When("I navigate to the game play page");
#line 16
 testRunner.And("I click on the tile at coordinate 0,0");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column",
                        "NumberOfMinesSurroundedBy"});
            table3.AddRow(new string[] {
                        "0",
                        "0",
                        "1"});
#line 17
 testRunner.Then("the following tiles should be revealed:", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column"});
            table4.AddRow(new string[] {
                        "1",
                        "1"});
            table4.AddRow(new string[] {
                        "0",
                        "1"});
            table4.AddRow(new string[] {
                        "0",
                        "2"});
            table4.AddRow(new string[] {
                        "1",
                        "0"});
            table4.AddRow(new string[] {
                        "1",
                        "2"});
            table4.AddRow(new string[] {
                        "2",
                        "0"});
            table4.AddRow(new string[] {
                        "2",
                        "1"});
            table4.AddRow(new string[] {
                        "2",
                        "2"});
#line 20
 testRunner.And("the following tiles should not be revealed:", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Click a tile that is not next to a minefield that contains one mine")]
        public virtual void ClickATileThatIsNotNextToAMinefieldThatContainsOneMine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Click a tile that is not next to a minefield that contains one mine", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I have started a new game \"minefield size of 9 x 9 (10 mines)\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column"});
            table5.AddRow(new string[] {
                        "2",
                        "2"});
#line 33
 testRunner.And("the minefield contains the following mines:", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column",
                        "NumberOfMinesSurroundedBy"});
            table6.AddRow(new string[] {
                        "1",
                        "1",
                        "1"});
            table6.AddRow(new string[] {
                        "1",
                        "2",
                        "1"});
            table6.AddRow(new string[] {
                        "2",
                        "1",
                        "1"});
#line 36
 testRunner.And("the following tiles are surrounded by mines:", ((string)(null)), table6);
#line 41
 testRunner.When("I navigate to the game play page");
#line 42
 testRunner.And("I click on the tile at coordinate 0,0");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column",
                        "NumberOfMinesSurroundedBy"});
            table7.AddRow(new string[] {
                        "0",
                        "0",
                        "0"});
            table7.AddRow(new string[] {
                        "0",
                        "1",
                        "0"});
            table7.AddRow(new string[] {
                        "0",
                        "2",
                        "0"});
            table7.AddRow(new string[] {
                        "1",
                        "0",
                        "0"});
            table7.AddRow(new string[] {
                        "1",
                        "1",
                        "1"});
            table7.AddRow(new string[] {
                        "1",
                        "2",
                        "1"});
            table7.AddRow(new string[] {
                        "2",
                        "0",
                        "0"});
            table7.AddRow(new string[] {
                        "2",
                        "1",
                        "1"});
#line 43
 testRunner.Then("the following tiles should be revealed:", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column"});
            table8.AddRow(new string[] {
                        "2",
                        "2"});
#line 53
 testRunner.And("the following tiles should not be revealed:", ((string)(null)), table8);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
