// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Columbo.Minesweeper.Specs.Uat.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Winning A Game")]
    public partial class WinningAGameFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Winning.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Winning A Game", "In order to win a game\r\nAs a player\r\nI need to remove all tiles that aren\'t mines" +
                    "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reveal all tiles that aren\'t mines and win the game")]
        public virtual void RevealAllTilesThatArenTMinesAndWinTheGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reveal all tiles that aren\'t mines and win the game", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have started a new game \"minefield size of 9 x 9 (10 mines)\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column"});
            table1.AddRow(new string[] {
                        "2",
                        "2"});
#line 8
 testRunner.And("the minefield contains the following mines:", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column",
                        "NumberOfMinesSurroundedBy"});
            table2.AddRow(new string[] {
                        "1",
                        "1",
                        "1"});
            table2.AddRow(new string[] {
                        "1",
                        "2",
                        "1"});
            table2.AddRow(new string[] {
                        "2",
                        "1",
                        "1"});
#line 11
 testRunner.And("the following tiles are surrounded by mines:", ((string)(null)), table2);
#line 16
 testRunner.When("I navigate to the game play page");
#line 17
 testRunner.And("I click on the tile at coordinate 0,0");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column",
                        "NumberOfMinesSurroundedBy"});
            table3.AddRow(new string[] {
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "1",
                        "1",
                        "1"});
            table3.AddRow(new string[] {
                        "0",
                        "1",
                        "0"});
            table3.AddRow(new string[] {
                        "0",
                        "2",
                        "0"});
            table3.AddRow(new string[] {
                        "1",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "1",
                        "2",
                        "1"});
            table3.AddRow(new string[] {
                        "2",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "2",
                        "1",
                        "1"});
#line 18
 testRunner.Then("the following tiles should be revealed:", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column"});
            table4.AddRow(new string[] {
                        "2",
                        "2"});
#line 28
 testRunner.And("the following tiles should not be revealed:", ((string)(null)), table4);
#line 31
 testRunner.And("I should see a message telling me that \"You have won!\"");
#line 32
 testRunner.And("I should see a button labelled \"Start New Game\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
