BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Games ADD
	Has_Lost bit NOT NULL CONSTRAINT DF_Games_Has_Lost DEFAULT 0
GO
ALTER TABLE dbo.Games SET (LOCK_ESCALATION = TABLE)
GO
COMMIT